/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Business.Ped_ProdBusiness;
import Business.PedidoBusiness;
import Business.ProdutoBusiness;
import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import model.Ped_Prod;
import model.Pedido;
import tablemodel.CarrinhoTableModel;
import tablemodel.GenericTableModel;

/**
 *
 * @author cristhian_anacleto
 */
public class FinalizarPedido extends javax.swing.JDialog {

    private NovoPedidoProduto novoPedidoProduto;
    private List<Ped_Prod> carrinho;
    
    private GenericTableModel gtmCarrinho;
    
    /**
     * Creates new form FinalizarPedido
     */
    public FinalizarPedido(java.awt.Frame parent, boolean modal, NovoPedidoProduto novoPedidoProduto, List<Ped_Prod> carrinho) {
        super(parent, modal);
        initComponents();
        this.novoPedidoProduto = novoPedidoProduto;
        this.carrinho = carrinho;
        
        gtmCarrinho = new CarrinhoTableModel(Ped_Prod.class, new String[]{"produto", "quantidade", "preço unitário", "valor total"});
        gtmCarrinho.setObjectList(carrinho);
        jTable1.setModel(gtmCarrinho);
        
        double valor = 0;
        for (Object listaCarrinho : gtmCarrinho.getObjectList()) {
            Ped_Prod pedProd = (Ped_Prod) listaCarrinho;
            valor += pedProd.getPrecoTotal();
        }
        labelTotal.setText(valor + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar Compra");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cartão de Crédito", "Dinheiro Físico" }));

        jLabel1.setText("Selecione a forma de pagamento:");

        jLabel2.setText("Preço Total:");

        labelTotal.setText("total");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finalizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTotal)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelTotal))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        novoPedidoProduto.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Cria o pedido e o registra no Banco de dados
        Pedido pedido = new Pedido();
        pedido.setCliente(novoPedidoProduto.getCliente());
        pedido.setDataPedido(Date.valueOf(LocalDate.now()));
        pedido.setFormaPagamento(comboBox.getSelectedIndex() + 1);
        pedido = PedidoBusiness.create(pedido);
        
        //Adiciona o pedido em cada pedProd, adiciona todos os pedProds no banco, e ajusta o estoque de produtos
        carrinho = Ped_ProdBusiness.adcPedido(carrinho, pedido);
        Ped_ProdBusiness.create(carrinho);
        Ped_ProdBusiness.ajustarEstoque(carrinho);
        
        this.dispose();
        
        novoPedidoProduto.getNovoPedidoCliente().getTelaPedido().setPedidos(PedidoBusiness.findAll());
        novoPedidoProduto.getNovoPedidoCliente().getTelaPedido().buscar();
        
        novoPedidoProduto.getNovoPedidoCliente().getTelaPedido().getTelaPrincipal().getTelaProduto().setProdutos(ProdutoBusiness.findAll());
        novoPedidoProduto.getNovoPedidoCliente().getTelaPedido().getTelaPrincipal().getTelaProduto().buscar();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelTotal;
    // End of variables declaration//GEN-END:variables
}
