/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Business.ProdutoBusiness;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import model.Cliente;
import model.Ped_Prod;
import model.Produto;
import tablemodel.CarrinhoTableModel;
import tablemodel.GenericTableModel;
import tablemodel.ProdutoTableModel;

/**
 *
 * @author cristhian_anacleto
 */
public class NovoPedidoProduto extends javax.swing.JDialog {

    private GenericTableModel gtmProduto;
    private GenericTableModel gtmCarrinho;
    private Cliente cliente;
    private NovoPedidoCliente novoPedidoCliente;

    private List<Ped_Prod> carrinho = new ArrayList();
    private List<Ped_Prod> carrinhoFiltered = new ArrayList();
    
    private List<Produto> produtos = ProdutoBusiness.findActive();
    private List<Produto> produtosFiltered;

    /**
     * Creates new form NovoPedidoProduto
     */
    public NovoPedidoProduto(java.awt.Frame parent, boolean modal, Cliente cliente, NovoPedidoCliente novoPedidoCliente) {
        super(parent, modal);
        initComponents();

        gtmProduto = new ProdutoTableModel(Produto.class, new String[]{"id", "nome", "quantidade", "preço"});
        gtmProduto.setObjectList(produtos);
        produtosFiltered = produtos;
        jTable1.setModel(gtmProduto);

        gtmCarrinho = new CarrinhoTableModel(Ped_Prod.class, new String[]{"produto", "quantidade", "preço unitário", "valor total"});
        jTable2.setModel(gtmCarrinho);

        this.cliente = cliente;
        this.novoPedidoCliente = novoPedidoCliente;
        
        spnQtd.setModel(new SpinnerNumberModel(1.0, Integer.MIN_VALUE, Double.MAX_VALUE, 1.0));
    }

    public Cliente getCliente() {
        return cliente;
    }
    
    public NovoPedidoCliente getNovoPedidoCliente() {
        return novoPedidoCliente;
    }
    
    public void atualizaTableProd() {
        gtmProduto.setObjectList(produtosFiltered);
    }
    
    public void atualizaTableCar() {
        gtmCarrinho.setObjectList(carrinhoFiltered);
        double valor = 0;
        for (Object listaCarrinho : carrinho) {
            Ped_Prod pedProd = (Ped_Prod) listaCarrinho;
            valor += pedProd.getPrecoTotal();
        }
        labelTotal.setText(valor + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        spnQtd = new javax.swing.JSpinner();
        btnAdc = new javax.swing.JButton();
        btnRmv = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnAvanc = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        btnBuscaProd = new javax.swing.JButton();
        txtBuscaProd = new javax.swing.JTextField();
        comboBoxProd = new javax.swing.JComboBox();
        comboBoxCar = new javax.swing.JComboBox();
        txtBuscaCar = new javax.swing.JTextField();
        btnBuscaCar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Produtos");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Realizar Pedido");

        jLabel2.setText("Selecionar");

        jLabel3.setText("Quantidade:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("Carrinho:");

        spnQtd.setEnabled(false);
        spnQtd.setValue(1);

        btnAdc.setText("Adicionar");
        btnAdc.setEnabled(false);
        btnAdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdcActionPerformed(evt);
            }
        });

        btnRmv.setText("Remover");
        btnRmv.setEnabled(false);
        btnRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnAvanc.setText("Avançar");
        btnAvanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancActionPerformed(evt);
            }
        });

        jLabel5.setText("Total:");

        labelTotal.setText("0");

        btnBuscaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        btnBuscaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaProdActionPerformed(evt);
            }
        });
        btnBuscaProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscaProdKeyPressed(evt);
            }
        });

        txtBuscaProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaProdKeyPressed(evt);
            }
        });

        comboBoxProd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Nome" }));
        comboBoxProd.setSelectedIndex(1);

        comboBoxCar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Nome" }));
        comboBoxCar.setSelectedIndex(1);

        txtBuscaCar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaCarKeyPressed(evt);
            }
        });

        btnBuscaCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        btnBuscaCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCarActionPerformed(evt);
            }
        });
        btnBuscaCar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscaCarKeyPressed(evt);
            }
        });

        jLabel6.setText("Produtos:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png"))); // NOI18N
        jLabel7.setText("Aviso:");

        jLabel8.setText("Para quantidades ");

        jLabel9.setText("decimais, utilize vírgula para");

        jLabel10.setText("separar os números");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdc))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAvanc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRmv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTotal))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscaCar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscaCar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBuscaCar)
                                .addComponent(comboBoxCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscaCar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBuscaProd)
                                    .addComponent(comboBoxProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnBuscaProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdc)
                        .addComponent(btnRmv)
                        .addComponent(jLabel5)
                        .addComponent(labelTotal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAvanc)
                                    .addComponent(jButton3))))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaCarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscaCarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscaCarActionPerformed(null);
        }
    }//GEN-LAST:event_btnBuscaCarKeyPressed

    private void btnBuscaCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCarActionPerformed
        // TODO add your handling code here:
        jTable1.clearSelection();
        btnAdc.setEnabled(false);
        btnRmv.setEnabled(false);
        spnQtd.setEnabled(false);

        String search = txtBuscaCar.getText();
        String type;

        if (comboBoxCar.getSelectedIndex() == 0) {
            type = "id";
        } else {
            type = "nome";
        }

        carrinhoFiltered = Ped_Prod.filter(carrinho, type, search);
        atualizaTableCar();
    }//GEN-LAST:event_btnBuscaCarActionPerformed

    private void txtBuscaCarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaCarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscaCarActionPerformed(null);
        }
    }//GEN-LAST:event_txtBuscaCarKeyPressed

    private void txtBuscaProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaProdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscaProdActionPerformed(null);
        }
    }//GEN-LAST:event_txtBuscaProdKeyPressed

    private void btnBuscaProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscaProdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscaProdActionPerformed(null);
        }
    }//GEN-LAST:event_btnBuscaProdKeyPressed

    private void btnBuscaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaProdActionPerformed
        // TODO add your handling code here:
        jTable1.clearSelection();
        btnAdc.setEnabled(false);
        btnRmv.setEnabled(false);
        spnQtd.setEnabled(false);

        String search = txtBuscaProd.getText();
        String type;

        if (comboBoxProd.getSelectedIndex() == 0) {
            type = "id";
        } else {
            type = "nome";
        }

        produtosFiltered = Produto.filter(produtos, type, search);
        atualizaTableProd();
    }//GEN-LAST:event_btnBuscaProdActionPerformed

    private void btnAvancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancActionPerformed
        // TODO add your handling code here:
        if (carrinho.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não há produtos no carrinho", "Erro", 0);
            return;
        }
        this.dispose();
        new FinalizarPedido(null, true, this, carrinho).setVisible(true);
    }//GEN-LAST:event_btnAvancActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        novoPedidoCliente.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvActionPerformed

        //PedProd selecionado na tabela do carrinho
        Ped_Prod pedProd = (Ped_Prod)gtmCarrinho.getObjectList().get(jTable2.getSelectedRow());
        Produto produto = pedProd.getProduto();

        double quantidade = (Double) spnQtd.getValue();

        //Verificação da quantidade selecionada
        if (quantidade > pedProd.getQuantidadeItem()) {
            JOptionPane.showMessageDialog(null, "Não há tantos itens no carrinho!", "Aviso", 2);
            return;
        }
        if (!(quantidade > 0)) {
            JOptionPane.showMessageDialog(null, "Coloque apenas quantidades válidas", "Aviso", 2);
            return;
        }

        for (int i = 0; i < carrinho.size(); i++) {
            if (carrinho.get(i) == pedProd) {
                carrinho.get(i).setQuantidadeItem(carrinho.get(i).getQuantidadeItem() - quantidade);
                if (carrinho.get(i).getQuantidadeItem() == 0) {
                    carrinho.remove(i);
                }
            }
        }

        if (produtos.contains(produto)){
            produto.setQuantidade(quantidade + produto.getQuantidade());
            gtmProduto.fireTableDataChanged();
        } else {
            produto.setQuantidade(quantidade);
            produtos.add(produto);
            gtmProduto.setObjectList(produtos);
        }

        btnBuscaProdActionPerformed(null);
        btnBuscaCarActionPerformed(null);

        jTable2.clearSelection();
        spnQtd.setValue(1.0);
        btnRmv.setEnabled(false);
        spnQtd.setEnabled(false);
    }//GEN-LAST:event_btnRmvActionPerformed

    private void btnAdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcActionPerformed
        // TODO add your handling code here:

        //Produto que está selecionado na tabela
        Produto produto = (Produto) gtmProduto.getObjectList().get(jTable1.getSelectedRow());

        //verificação de quantidades
        if (!((Double) spnQtd.getValue() > 0)) {
            JOptionPane.showMessageDialog(null, "Utilize somente quantidades válidas!", "Aviso", 2);
            return;
        }

        if ((Double) spnQtd.getValue() > produto.getQuantidade()) {
            JOptionPane.showMessageDialog(null, "Não há produtos suficientes no estoque!", "Aviso", 2);
            return;
        }

        //Verifica se o produto selecionado já está no carrinho
        boolean verif = false;
        for (int i = 0; i < carrinho.size(); i++) {
            if (carrinho.get(i).getProduto() == produto) {
                carrinho.get(i).setQuantidadeItem(carrinho.get(i).getQuantidadeItem() + (Double) spnQtd.getValue());
                verif = true;
            }
        }

        //Cria o pedProd que ficará armazenado dentro do carrinho, caso o produto ainda não esteja no carinho
        if (!verif) {
            Ped_Prod pedProd = new Ped_Prod();
            pedProd.setProduto(produto);
            pedProd.setPrecoItem(produto.getPrecoReferencia());
            pedProd.setQuantidadeItem((Double) spnQtd.getValue());

            carrinho.add(pedProd);
        }

        //Altera a quantidade do produto na tabela de produtos em estoque
        produto.setQuantidade(produto.getQuantidade() - (Double) spnQtd.getValue());
        if (produto.getQuantidade() == 0) {
            produtos.remove(produto);
        }
        gtmProduto.setObjectList(produtos);

        btnBuscaCarActionPerformed(null);
        btnBuscaProdActionPerformed(null);
        //Realiza as operaçãos de habilitação e desabilitação de botões
        btnAdc.setEnabled(false);
        spnQtd.setEnabled(false);
        spnQtd.setValue(1.0);
        jTable1.clearSelection();
    }//GEN-LAST:event_btnAdcActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        jTable1.clearSelection();
        btnAdc.setEnabled(false);
        btnRmv.setEnabled(true);
        spnQtd.setEnabled(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jTable2.clearSelection();
        btnRmv.setEnabled(false);
        btnAdc.setEnabled(true);
        spnQtd.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdc;
    private javax.swing.JButton btnAvanc;
    private javax.swing.JButton btnBuscaCar;
    private javax.swing.JButton btnBuscaProd;
    private javax.swing.JButton btnRmv;
    private javax.swing.JComboBox comboBoxCar;
    private javax.swing.JComboBox comboBoxProd;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JSpinner spnQtd;
    private javax.swing.JTextField txtBuscaCar;
    private javax.swing.JTextField txtBuscaProd;
    // End of variables declaration//GEN-END:variables
}
